Mobile version
TemesgenA/portfolio pull request #2
Opened 2022-05-28 22:46 UTC by TemesgenA

## Mobile Version
Knowledge implemented:
- Understand how to parse a Figma design to create a UI.
- Use Flexbox to place elements on the page.
- Use CSS Grid to place elements on the page.
- Build a personal portfolio site.

2022-05-28 23:36 UTC, micheaol requested changes
Hi @TemesgenA , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## TO HIGHLIGHT: 
- Your project is professional 💯 
- Your repo is professional 💯 
- Well structured files 💯 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-05-28 23:36 UTC, micheaol commented on index.html
> +                </ul>
Please ensure that the list of icons uses a `ul` tag to group them, and `li` per icon; each icon has `a link (`a` tag)` according to the project requirement.

2022-05-28 23:36 UTC, micheaol commented on index.html
> +                    <li><i class="fa fa-github" aria-hidden="true"></i></li>
Please ensure that each section has the margins (top, bottom, left, right) defined in the design, and the font and colors (background and font) defined for the template according to the project requirement.

2022-06-02 19:55 UTC, m05e5 approved these changes
# Hi @TemesgenA , 

### Status: Approved ✔️
![goodjob](https://user-images.githubusercontent.com/60631456/130260474-3c2d5e5c-96df-43de-a0db-8d0059c10862.gif)


:+1: You have done all the required changes asked by the previous reviewer. Well Done.

Your project is complete! 
Congratulations! 🎉 


**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
-----

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_m05e5_**

------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-02 19:57 UTC, merged